function skillsMember()
{
    return [
        'HTML',
        'CSS',
        'JavaScript',
        'React',
        'NodeJS',
        'Express',
        'MongoDB',
        'PostgreSQL',
        'Docker',
        'Kubernetes',
        'AWS',
        'GCP',
        'Azure',
        'Python',
        'Java',
        'C#',
        'C++',
        'Ruby',
        'PHP',
        'Swift',
        'Objective-C',
        'Kotlin',
        'Perl',
        'Rust',
        'Go',
        'Scala',
        'Haskell',
        'Clojure',
        'R',
        'Julia',
        'TypeScript',
        'Angular',
        'Vue',
        'Ruby on Rails',
        'Django',
        'Spring',
        'ASP.NET',
        'Flask',
        'Laravel',
        'Symfony',
        'Express',
        'NestJS',
        'Strapi',
        'KeystoneJS',
        'Ghost',
        'Drupal',
        'WordPress',
        'Joomla',
        'Magento',
        'Shopify',
        'PrestaShop',
        'BigCommerce',
        'WooCommerce',
        'Squarespace',
        'Wix',
        'Weebly',
        'Webflow',
        'Elementor',
        'Gutenberg',
        'Bootstrap',
        'Tailwind CSS',
        'Material UI',
        'Semantic UI',
        'Bulma',
        'Ant Design',
        'Chakra UI',
        'Rebass',
        'Styled Components',
        'Emotion',
        'JSS',
        'JSS',
        'CSS Modules',
        'Sass',
        'Less',
        'Stylus',
        'PostCSS',
        'Webpack',
        'Parcel',
        'Rollup',
        'Gulp',
        'Grunt',
        'Babel',
        'TypeScript',
        'Flow',
        'ESLint',
        'Prettier',
        'Jest',
        'Mocha',
        'Chai',
        'Enzyme',
        'Cypress',
        'React Testing Library',
        'Jasmine',
        'Karma',
        'AVA',
        'Tape',
        'Supertest',
        'Nock',
        'Sinon',
        'Chai',
        'Jest',
        'Mocha',
